### ISSUE TITLE
Workshop - Speeding everyone up on Docker

### ISSUE THREAD

**Issue by daviddias** [dockerlisbon/community#13]
Similar to NodeSchool, we can start doing a speeding up on Docker following 
- http://blog.flux7.com/blogs/docker/docker-tutorial-series-part-1-an-introduction
- http://blog.flux7.com/blogs/docker/docker-tutorial-series-part-2-the-15-commands
- http://blog.flux7.com/blogs/docker/docker-tutorial-series-part-3-automation-is-the-word-using-dockerfile
- http://blog.flux7.com/blogs/docker/docker-tutorial-series-part-4-registry-workflows
- http://blog.flux7.com/blogs/docker/docker-tutorial-series-part-5-docker-security
- http://blog.flux7.com/blogs/docker/docker-commands
- http://blog.flux7.com/blogs/docker/docker-tutorial-series-part-7-ultimate-guide-for-docker-apis
- http://blog.flux7.com/blogs/docker/docker-tutorial-series-part-8-docker-remote-api

What do you say?

**People that offered to Mentor this:**
- Pedro Dias @apocas

**Comment by pierreozoux** [comment]
I'm in also to help organizing that!
How do you usually do? Do you need a short introduction on docker?
I work everyday with Docker and CoreOS, so I'd be more than happy to share what I know and learn what I still miss :)

**Comment by diasdavid** [comment]
We need more folks playing with the technology, all the input and mentoring is welcome. I believe having tutorials is awesome so everyone has a beginners path, but we definitely need people with experience to tell how all this works

**Comment by diasdavid** [comment]
Let's pick a date, this month is already quite full with JS meetups, what about April?

**Comment by pierreozoux** [comment]
From the 15th is good for me. Do you have a place for that already?

**Comment by diasdavid** [comment]
We can use the Blue office, there is enough good wifi and power outlets all over :)

**Comment by pierreozoux** [comment]
Good :) I don't know them, so I let yo get in touch and decide the date :)
If you need help on anything, let me know!

**Comment by pierreozoux** [comment]
Anybody still interested?

A little docker school 101 :) How to get your first container running?
