### ISSUE TITLE
Global Docker Hack Day

### ISSUE THREAD

**Issue by daviddias** [dockerlisbon/community#16]
![](https://blog.docker.com/media/2015/07/globalhackday3.png)

Hi everyone!

Just received an inquiry from Docker to ask of our interest to organize the next Docker Hack day! Here is the message:

> Hello Docker Meetup Organizers!
> 
> Today, we are incredibly excited to announce Docker Global Hack Day #3 (GHD). Since Docker GHD #2 last October, the number of Docker meetup groups has doubled. Thank you for all of your efforts in helping the Docker Community reach this amazing achievement of 200 Docker meetup groups worldwide! 
> 
> To make this Hack Day really global, we need your help to organize as many local editions as possible. 
> 
> What we will provide:
> - A livestream and video recording of the event in San Francisco on September 16th
> - Our presentation / Release materials for you to use
> - Special T-shirts & Stickers for the attendees
> - Promotion for the event on our website, weekly newsletter and social media
> - Remote engineering support via IRC
> 
> **What we need your help with:**
> - Selecting a venue, date and time for the event sometime between September 16th and Sept 21st.
> - Find potential Food & Beverages sponsors. We can potentially help where there are none available.
> - Potentially recruit other organizers to help with logistics / mentoring associated with this hands on hackday
> - Share the Global Hack Day information with the attendees at the event
> - Share the details with us so we can help promote
> - Send us your mailing address ASAP so we can send you the special edition t-shirts and stickers
> 
> Please let us know if you're available / interested in working with us to put together a local edition in your city!
> 
> Thank you so much for everything you do for the Docker Community in your cities. We feel very fortunate to be working with you all. 
> 
> Thanks,
> 
> Victor and Katya

My first thought was, hell yeah! :D 

So, who is in to help org this event? @xicombd, Pedro Saraiva, Cláudia Filipe (@Claudiabf), would the SINFO team be up? @rcarmo, following our email thread, does this look like a good event to Sapo take part of making it happen?

The last Docker Party we had, we completely excited the YLD Lisbon HQ capacity, over 50 people in workshop set up is hard, specially taking into account having wifi for all (Docker is kind of expensive in terms of bandwidth)

**Announcement blost post: https://blog.docker.com/2015/07/announcing-docker-global-hack-day-3/**

**Comment by rcarmo** [comment]
Hello guys, 

Here @sapo we’ll be working on the Lisbon Maker Faire (http://makerfairelisbon.com/en/ http://makerfairelisbon.com/en/) until September 20th, but we’re open to making our auditorium available to you for presentations.

Workshops, realistically, not so much - we can spare the bandwidth, but we just don’t have the space offhand to provide 50-odd people a proper desk to work on (even though the auditorium will sit 50 and there’s a reason those things are called “laptops”, it’s not the best way to work, and for a proper hackathon we'll need another venue).

If you’re willing to do, say, presentations on one day and workshops on the other, 16th _might_ be doable for us to have you at SAPO HQ for the first part, but since the Maker Faire opens to the public on the 18th, it’s a very tight window… 

We will be glad to speak at the event, though, and there might be other options for helping out.

**Comment by pierreozoux** [comment]
I'd be glad to help by running a hackathon about the following: https://github.com/weihanwang/docker-ecosystem-survey/issues/4

a 4h slot would be amazing!

Please let me know!

**Comment by daviddias** [comment]
I believe that doing a 5 day hackathon is super ambitious and probably wouldn't work for the size/audience of the event. 

It would be good to have the `kickoff` day on the 16th, get everyone up to speed, set expectations and have people @pierreozoux doing a workshop. 

From the 16th to the 21st, we could have some space at IST, StartupLX, or another space that would be interested to host a temporary co-work space for the hackathon, so participants had a good place to work and find each other.

And since Maker Faire is happening, on the 18th~20th, we can have an extra meetup with more talks, where the hackathon participants could share an update on what they have built so far.

Thoughts?

**Comment by pierreozoux** [comment]
Pff, actually 15/16, I might be out of the city, waiting for confirmation :/ I think I'm cursed with Lisbon Docker events :)

**Comment by rcarmo** [comment]
Just to tease you, the weather is sure to be great by that time ;)

**Comment by JGAntunes** [comment]
@diasdavid we at @sinfo are definitely in! We could help on finding potential food & beverages sponsors (besides all the usual stuff we may help on).

As for the venue, if there's no other choice, we could see if we could work out something at IST, although getting a space reserved for this for 5 days will probably be a bit hard.

**Comment by daviddias** [comment]
One of the things I noticed, comparing to the last hackathon, is that for this Hack Day, it is required that folks come up with new ideas and develop them during window of time available. It would be interesting to know first how many people will be interested in doing something for the event, in order to properly organize an hacking space for them.

So, here is my proposal for a **plan**:
- The Global Hackathon will start officially on the Wednesday 23:59h Lisbon Time September 16th.
- Organize a regular meetup with talks and as a kick off, on Wed Sep 16th from 7pm to 9pm
  - talk by the Sapo team
  - speaker 2
  - speaker 3
  - venue: Sapo
- Get a space\* where teams can get access to and work during the following days 
  - some options that come to mind: IST, StartupLX, YLD! Lisbon HQ
- Have a special meetup at Lisbon Maker Faire with @pierreozoux 4hour workshop on the 19th or 20th

[*] while we announce the meetup and Global Hack Day, we gather the interest from teams in Lisbon to participate in the hackthon and prepare a proper workspace accordingly.

**Comment by rcarmo** [comment]
Hi there again!

There might be issues with using the auditorium outside "regular" work hours - I'm going to check, but our usual afternoon event schedule is more along the lines of 5pm to 7pm (we also do a fair amount of stuff in the mornings).

**Comment by daviddias** [comment]
Got a ping back from Docker, they want to announce the cities that will host events :) 

@rcarmo any updates on the Venue? Can we also get an update on the talk?

@pierreozoux do you have any update on your schedule? 

@JGAntunes @claudiabf @sinfo would you be able to handle event logistics on the ground?

**Comment by pierreozoux** [comment]
@diasdavid still waiting confirmation. For my part, I'm sure at 90% that 15/16, I'll be in France.
So, yes, I can confirm for 100% that 19th or 20th, I'm available to make this workshop!

_excited_

**Comment by JGAntunes** [comment]
@diasdavid count us in! ;)

**Comment by daviddias** [comment]
Awesome! Let's announce this thing :) 

FYI, @JGAntunes and @claudiabf will be leading the event with the rest of the SINFO team :) which means the event will be awesome!!

**Comment by JGAntunes** [comment]
Hey guys!
@rcarmo any news on the venue/talk?
@diasdavid do you think we could use YLD! Lisbon HQ as venue? At least as a space where teams could work the following days.

**Comment by daviddias** [comment]
We always have free desks, pretty sure it won't be a problem :)

**Comment by rcarmo** [comment]
Hi there! I'm on vacation for a few weeks and lost track of this discussion until now, but like I said before, that time schedule would be tricky. Also, keep in mind that we'll be having the Maker Faire later that week, so we'll be focusing on that...

**Comment by JGAntunes** [comment]
@rcarmo yeah it seems it will be a bit complicated, let's leave this for a next time maybe ;)

As for the event, I've talked a bit with @diasdavid and we came to a conclusion that maybe we were being over ambitious so, what I would like to purpose, is that we kick this off **September 19th** with a talk by a guest speaker, followed by @pierreozoux workshop and then hack the day away \o/ This would take place at Microsoft offices here Lisbon, as they were kind enough to provide us with space and a coffee break!

What do you say? Ready for a kick ass event!?

**Comment by pierreozoux** [comment]
I'm ready :) !

**Comment by JGAntunes** [comment]
It's [alive](http://www.meetup.com/DockerLisbon/events/224906676/)!!!

**Comment by daviddias** [comment]
Woot! :D

**Comment by JGAntunes** [comment]
@pierreozoux do you have any time estimate for the workshop? (plus any special stuff you or the audience might need?)
As for the rest, we were thinking on starting at **10 AM** with a simple 5/10 minute opening (@pierreozoux care to do the honors? :D) followed by microsoft guest speaker 45 min presentation. Then we would have @pierreozoux ws (maybe with a break for launch or, if not advisable to stop, starting after launch). Finally we would hack away through the afternoon with a coffee break powered by microsoft \o/
cc/ @palma21 who will be our contact there.

**Comment by palma21** [comment]
Me :)
If there's anything you need, let me know

-----Original Message-----

**Comment by pierreozoux** [comment]
@JGAntunes It is on my todo, I'll send you that today or tomorrow! Thanks :)

**Comment by JGAntunes** [comment]
@pierreozoux no problem, just ping me when you've got more info ;)

**Comment by pierreozoux** [comment]
WorkShop description

------------------->8--------------------

## Help map the docker ecosystem

Docker is a lovely tool. It's best feature is the clean contract it offers with the service. `docker run`! [12factor](http://12factor.net/) dreamt about it, docker did it.

We can now dream about our personal PaaS! Well it is not that easy...

[As](https://github.com/weihanwang/docker-ecosystem-survey) [you](https://www.quora.com/What-is-the-best-Docker-Linux-Container-orchestration-tool) [can](http://stackoverflow.com/questions/18285212/how-to-scale-docker-containers-in-production/18287169#18287169) [see](https://www.mindmeister.com/389671722/docker-ecosystem), there are lot of actors our there. In this jungle, I have to admit, I'm lost.

You might have heard of the [ToDoMVC](http://todomvc.com/) to compare javascript framework? Let's do the same to help you select the right docker orchestration framework.

The project is called `wordpress docker orchestration` and the goal is to take this minimum/classical setup:
https://github.com/paulczar/docker-wordpress (one server, bash)
And make it fit in all the orchestration tools available out there.

Then we'll have a clean way to compare kubernetes to deis to dokku to rancher to < you name it >

------------------->8--------------------

Please do not hesitate to comment on whatever @dockerlisbon/community I'd love to hear your feedback on this proposition, and then we can put it on the meetup description.

@JGAntunes I think the timetable fit. I can present the event if you want. for lunch, 
I think  it is not a big deal if it is cut by lunch.
I'll personally work all the day on that.
I think it is more a call to participate than a workshop. People should be free to do their own stuff on their side, or join us having fun discovering those amazing tools!

**Comment by JGAntunes** [comment]
@pierreozoux awesome then! I definitely agree with you, that's why we're going to have the presentation first and then people can either collaborate on this or work on whatever they want :) either way I'm going to update the meetup description with this and the agenda for the day.

Thank you ;)

**Comment by pierreozoux** [comment]
Ok. I think we can close this issue :)

**Comment by JGAntunes** [comment]
You're right! @diasdavid care to close this please :)

**Comment by daviddias** [comment]
You are all awesome! Thank you for making it happen!!! 

![](https://media.giphy.com/media/O0oQygeklvnX2/giphy.gif)

**Comment by pierreozoux** [comment]
Yep!

Can we close this issue? (I don't have write perm)

**Comment by daviddias** [comment]
absolutely :)
