### ISSUE TITLE
talk proposal: kubernetes vs compose

### ISSUE THREAD

**Issue by pierreozoux** [dockerlisbon/community#17]
I'm still working on this little project:
- https://github.com/Docker-Orchestration-Hello

I'd be happy to share my findings!

What do you think for end of November?

**Comment by lpalgarvio** [comment]
nice!

although i think it's more a question of kubernetes vs swarm (vs mesos vs rancher).
eventually, docker compose will have to be adopted by all frameworks.
it's official functionality and already too popular to be ignored.
