### ISSUE TITLE
Find a venue

### ISSUE THREAD

**Issue by pierreozoux** [dockerlisbon/community#21]
YLD?

**Comment by daviddias** [comment]
ping @sericaia for YLD space

Other great options include:
- Uniplaces (ping @jtascensao)
- http://www.startuplisboa.com/ (ping Ana Santiago)
- http://beta-i.pt/ (ping Ricardo Marvão)
- Webnographer (ping @jamespage)
- Microsoft Portugal (ping João Almeida)
- Premium Minds (ping @dzacarias)

Feel free to do some cross pollination and learn from `require('lx')` https://github.com/require-lx/community/tree/master/venues

**Comment by JGAntunes** [comment]
I can also check if we can do it at IST Alameda if you're interested.

**Comment by daviddias** [comment]
DO EEET :D

**Comment by dzacarias** [comment]
Hey guys

Can't make it to this one, but I've confirmed with @knokio and he can. Premium Minds would be more than happy to host you.

Feel free to reach out to him and get the ball rolling 😀

**Comment by knokio** [comment]
Hey there. Feel free to contact me to arrange the details

**Comment by lpalgarvio** [comment]
Some more here:
https://github.com/diasdavid/awesome-hacking-spots

I added MILL and Liberdade 229.
Liberdade 229 is a nice spot for up to 20-25 people.

**Comment by JGAntunes** [comment]
Just checked and SINFO can help with the venue if needed be. Let me know if you're up for it :+1:.

**Comment by daviddias** [comment]
@lpalgarvio I wouldn't consider https://github.com/diasdavid/awesome-hacking-spots as good spots for meetups, it is mostly coffee shops.

**Comment by pierreozoux** [comment]
@knokio Can you confirm the 29th November at 19pm?

Thanks a lot!

@JGAntunes Next time with SINFO with pleasure!

**Comment by lpalgarvio** [comment]
The places i mentioned are already insufficient! 40+ registered attendees.

**Comment by daviddias** [comment]
@knokio seems like all we need is your confirmation to announce the meetup everywhere :)

**Comment by knokio** [comment]
@diasdavid @pierreozoux Houston we have a confirmation for the 29th November 😃

**Comment by pierreozoux** [comment]
@knokio Thanks for that! What is the limit in term of attendees?

**Comment by knokio** [comment]
@pierreozoux around here we think the "good" limit is 48 attendees (there's room for some more if they decide to show up later). Is that ok?

**Comment by knokio** [comment]
@pierreozoux @diasdavid shoot me an email to arrange the details: dfigueiredo@pminds.pt or diogoepf@gmail.com

**Comment by daviddias** [comment]
Note that count like 60% of attendance from people that RSVP

**Comment by lpalgarvio** [comment]
=)
