### ISSUE TITLE
Find a date

### ISSUE THREAD

**Issue by pierreozoux** [dockerlisbon/community#22]
29th November?(30th is require(lx))

**Comment by lpalgarvio** [comment]
To organize this i believe we will have to do it between 20/Nov and 10/Dec

I think we can rule out these days:
24/Nov: lxjs
30/Nov: requirelx
06/Dec: requirelx
12/Dec: devopslisbon

29/Nov gives us ~2 weeks to plan. Workday, mid week. Sounds good!
Else, the 7/Dec might be another good day, just before DevOps Lisbon and with an extra week to plan.

**Comment by pierreozoux** [comment]
I'll be out of town the 7th :) That's why I choosed the 29th :)
