### ISSUE TITLE
Find 2 talks

### ISSUE THREAD

**Issue by pierreozoux** [dockerlisbon/community#23]
I can present 30min http://Libre.sh

**Comment by lpalgarvio** [comment]
I can add Docker High Performance PHP Stack:
https://github.com/solict/docker-high-performance-php-stack

Projected for 20-30min.

**Comment by daviddias** [comment]
@pierreozoux @lpalgarvio please update the meetup agenda https://www.meetup.com/DockerLisbon/events/219278512/ it is the main point where people get info about the meetup
