### ISSUE TITLE
Find a sponsor (drink/food)

### ISSUE THREAD

**Issue by pierreozoux** [dockerlisbon/community#24]
@daviddias any idea?

**Comment by daviddias** [comment]
It would be good to know what we are shooting here for. Drinks? Pizzas? Tacos? Number of expected people

**Comment by pierreozoux** [comment]
Drinks would already be amazing for a 2nd meetup, short-ish notice

**Comment by lpalgarvio** [comment]
I might get some support from Rosmaninho Arte & Aromas.
Full disclosure: family business
https://www.zomato.com/grande-lisboa/rosmaninho-arte-aromas-alg%C3%A9s-lisboa

**Comment by pierreozoux** [comment]
@lpalgarvio nice :)

**Comment by daviddias** [comment]
@lpalgarvio are we good with Rosmaninho? Will we have cookies? :D

**Comment by lpalgarvio** [comment]
Yes :)
They are preparing something for us. Will have more details tomorrow!

**Comment by lpalgarvio** [comment]
Here's what they will prepare:
- 2-3 big cakes
- cookies

They say enough for 50 people.
I will get some beer.
