### ISSUE TITLE
Announce the meetup once venue/date confirmed

### ISSUE THREAD

**Issue by pierreozoux** [dockerlisbon/community#25]
Arf, I can't send an email to all members...

@daviddias, do you knwo where to do that? Or do I need more permissions?

**Comment by lpalgarvio** [comment]
we are not yet coordinators in the meetup.com group.
can you add us?
https://www.meetup.com/pt-BR/DockerLisbon/members/?op=leaders
@pierreozoux @lpalgarvio @daviddias

**Comment by daviddias** [comment]
Just added you both :)
