### ISSUE TITLE
Socket activated docker

### ISSUE THREAD

**Issue by pierreozoux** [dockerlisbon/community#8]
Anybody has an idea about [that](https://stackoverflow.com/questions/24791648/start-docker-container-using-systemd-socket-activation)

Basically the use case is really simple: I have an nginx in a container, and I want to start it on incoming connection on port 80.
I think this is possible, but I didn't see anything nor anybody saying they did it with Docker.
If you have anything, please let me know :)

**Comment by davidstrauss** [comment]
Hi, I'm the author of socket-proxyd. Please let me know if you have any questions.

**Comment by pierreozoux** [comment]
Thanks, I think I'll wait for https://github.com/coreos/rocket/issues/106 to close and switch to rocket.
What is your idea on that?

The thing is that, I'm already using https://github.com/ibuildthecloud/systemd-docker, so if I add socket-proxyd, it will not just be smelly, it will stink :)

I think if it is solved at the container manager level, and if this container manager integrates well with systemd, then it is nice!

**Comment by davidstrauss** [comment]
> What is your idea on that?

Sounds good to me. Just offering my expertise because it's an area of systemd that only a few people understand well.

**Comment by pierreozoux** [comment]
Thanks for your input, I'll close this issue.
I have to switch to kubernetes before rkt :) But the issue is merged now on rkt code base.

I'm wondering about systemd-nspawn and runC though.
